global using FluentAssertions;
global using Func.Redis.Models;
global using MELT;
global using Microsoft.Extensions.Logging;
global using NSubstitute;
global using NUnit.Framework;
global using StackExchange.Redis;
global using TinyFp;
global using TinyFp.Extensions;
